# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Unit Tests

on:
    # Only for PR against master branch
    pull_request:
        branches: [master]

jobs:
    tests:
        runs-on: ${{ matrix.os }}

        strategy:
            matrix:
                os:
                    - ubuntu-latest
                    - macos-latest
                    - windows-latest
                node_version:
                    - 10
                    - 12
                    - 14
                node_arch:
                    - x64
                # an extra windows-x86 run:
                include:
                    - os: windows-2016
                      node_version: 12
                      node_arch: x86
                          - 14

        name: Node ${{ matrix.node_version }} - ${{ matrix.node_arch }} on ${{ matrix.os }}
        steps:
            - uses: actions/checkout@v2
            - name: Setup node
              uses: actions/setup-node@v1
              with:
                  node-version: ${{ matrix.node-version }}
                  node-arch: ${{ matrix.node_arch }}
            - run: npm install
            - run: npm test
